version: 2
jobs:
  build:
    machine:
      node:
        version: 6.1.0

    steps:
      - checkout

      - run:
          name: Install NPM
          command: npm i -g npm

      - run:
          name: Test datasource code
          command: npm run test

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: [master]
